version: '3.8'
services:
  service-db:
    image: postgres:15-alpine3.19
    env_file:
      - db.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d apartments" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - my_net
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
  backend:
    image: backend:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    networks:
      - my_net
    env_file:
      - back.env

volumes:
  db-data:

networks:
  my_net:
    driver: bridge